#!/usr/bin/env python3
"""Plot grouped bar charts from interactive_results_summary table JSON exports.

This script reads the JSON export produced by scripts/interactive_results_summary.py
and renders one grouped bar chart per table entry.

Behavior:
- Each row in a table becomes one x-axis group.
- The x-axis label value is taken from the row's group field (for example, real_images).
- Methods are derived from headers and row content.
- Baseline is placed as the left-most bar in each group when present in rows.
- If baseline is absent from rows, it is excluded.
- LaTeX-like values such as "72.9\\% $\\pm$ 1.44\\%" are parsed into mean/error.
- Error bars are shown when available.
- Figures are displayed in a window, and optionally saved with --output-dir.
"""

from __future__ import annotations

import argparse
import json
import math
import re
from importlib import import_module
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib import font_manager
import numpy as np


LATEX_VALUE_PATTERN = re.compile(
    r"""
    ^\s*
    (?P<mean>[-+]?\d*\.?\d+)
    \s*(?:\\%|%)?
    (?:
        \s*(?:\$?\\pm\$?|±|\+/-)\s*
        (?P<err>[-+]?\d*\.?\d+)
        \s*(?:\\%|%)?
    )?
    \s*$
    """,
    re.VERBOSE,
)


def legend_is_off(table: dict) -> bool:
    value = table.get("legend")
    return isinstance(value, str) and value.strip().lower() == "off"


def parse_bool(value: object, default: bool = True) -> bool:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return bool(value)
    if isinstance(value, str):
        cleaned = value.strip().lower()
        if cleaned in {"off", "false", "no", "0"}:
            return False
        if cleaned in {"on", "true", "yes", "1"}:
            return True
    return default


def parse_float(value: object) -> float | None:
    if value is None:
        return None
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return None
    if math.isnan(parsed):
        return None
    return parsed


def normalize_bar_spacing(value: object) -> float:
    parsed = parse_float(value)
    if parsed is None:
        return 0.0
    return min(max(parsed, 0.0), 0.8)


def normalize_bar_gap(value: object) -> float:
    parsed = parse_float(value)
    if parsed is None:
        return 0.0
    return min(max(parsed, 0.0), 2.0)


def configure_cmu_serif_font(font_dir: Path) -> None:
    if not font_dir.exists():
        return

    for font_path in font_dir.glob("*.ttf"):
        font_manager.fontManager.addfont(str(font_path))

    plt.rcParams.update(
        {
            "font.family": "CMU Serif",
            "mathtext.fontset": "cm",
            "mathtext.rm": "CMU Serif",
            "mathtext.it": "CMU Serif:italic",
            "mathtext.bf": "CMU Serif:bold",
        }
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot grouped bar charts from exported table.json files.",
    )
    parser.add_argument(
        "json_path",
        type=Path,
        help="Path to table.json generated by interactive_results_summary.py",
    )
    parser.add_argument(
        "--table-index",
        type=int,
        default=None,
        help=(
            "Optional table index in payload['tables'] to plot. "
            "If omitted, all tables are plotted."
        ),
    )
    parser.add_argument(
        "--group-field",
        type=str,
        default=None,
        help=(
            "Optional row key used for x-axis group labels (for example, real_images). "
            "If omitted, it is inferred from row keys."
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Optional directory to save PNG files. If omitted, figures are not saved.",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=200,
        help="DPI for saved figures.",
    )
    parser.add_argument(
        "--global",
        dest="global_range",
        action="store_true",
        help=(
            "Use global/full y-axis range behavior (current default matplotlib autoscaling). "
            "If omitted, y-axis is tightened around data min/max including error bars."
        ),
    )
    parser.add_argument(
        "--customize",
        action="store_true",
        help=(
            "Interactively choose chart grouping using method/split/ratio dimensions "
            "via python inquirer."
        ),
    )
    return parser.parse_args()


def get_inquirer_module():
    try:
        return import_module("inquirer")
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing dependency 'inquirer'. Install with: "
            "uv add inquirer or pip install inquirer"
        ) from exc


def prettify_label(name: str) -> str:
    return " ".join(part.capitalize() for part in name.replace("-", "_").split("_"))


def parse_latex_value(value: str) -> tuple[float, float]:
    if not isinstance(value, str):
        return math.nan, math.nan

    cleaned = value.strip()
    if not cleaned:
        return math.nan, math.nan

    match = LATEX_VALUE_PATTERN.match(cleaned)
    if not match:
        return math.nan, math.nan

    mean = float(match.group("mean"))
    err_raw = match.group("err")
    err = float(err_raw) if err_raw is not None else 0.0
    return mean, err


def infer_group_field(row: dict) -> str:
    candidates = [
        key
        for key, value in row.items()
        if key != "baseline" and not isinstance(value, (dict, list))
    ]
    if len(candidates) != 1:
        raise ValueError(
            "Could not infer a unique group field from row keys. "
            "Use --group-field explicitly. "
            f"Row keys: {sorted(row.keys())}"
        )
    return candidates[0]


def infer_method_container_key(rows: list[dict], group_field: str) -> str | None:
    candidate_keys = set()
    for row in rows:
        for key, value in row.items():
            if key in {"baseline", group_field}:
                continue
            if isinstance(value, dict):
                candidate_keys.add(key)

    if not candidate_keys:
        return None

    if len(candidate_keys) > 1:
        raise ValueError(
            "Found multiple candidate method container fields in rows: "
            f"{sorted(candidate_keys)}"
        )

    return next(iter(candidate_keys))


def extract_methods(
    table: dict,
    rows: list[dict],
    group_field: str,
) -> tuple[list[str], dict[str, str], str | None]:
    headers = table.get("headers") or []
    if not headers or len(headers) < 2:
        raise ValueError("Each table must provide at least two headers.")

    method_display_names = {}
    ordered_methods: list[str] = []
    method_container_key = infer_method_container_key(rows, group_field)

    baseline_present = any("baseline" in row for row in rows)
    if baseline_present:
        ordered_methods.append("baseline")
        method_display_names["baseline"] = prettify_label(headers[1])

    header_methods = headers[2:]
    for method_name in header_methods:
        if any(
            isinstance(row.get(method_container_key), dict)
            and method_name in row.get(method_container_key, {})
            for row in rows
        ):
            ordered_methods.append(method_name)
            method_display_names[method_name] = method_name

    if not ordered_methods:
        raise ValueError("No plottable methods found in rows.")

    return ordered_methods, method_display_names, method_container_key


def build_plot_arrays(
    rows: list[dict],
    group_field: str,
    ordered_methods: list[str],
    method_container_key: str | None,
) -> tuple[list[str], dict[str, np.ndarray], dict[str, np.ndarray]]:
    x_labels: list[str] = []
    values: dict[str, list[float]] = {method: [] for method in ordered_methods}
    errors: dict[str, list[float]] = {method: [] for method in ordered_methods}

    for row in rows:
        if group_field not in row:
            raise ValueError(f"Group field '{group_field}' not found in row: {row}")

        x_labels.append(str(row[group_field]))

        methods_data = {}
        if method_container_key is not None and isinstance(row.get(method_container_key), dict):
            methods_data = row.get(method_container_key) or {}
        for method in ordered_methods:
            if method == "baseline":
                mean, err = parse_latex_value(row.get("baseline", ""))
            else:
                mean, err = parse_latex_value(methods_data.get(method, ""))
            values[method].append(mean)
            errors[method].append(err)

    value_arrays = {name: np.array(vals, dtype=float) for name, vals in values.items()}
    error_arrays = {name: np.array(vals, dtype=float) for name, vals in errors.items()}
    return x_labels, value_arrays, error_arrays


def sanitize_filename(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", text).strip("_") or "plot"


def metric_ylabel(metric: str) -> str:
    title = prettify_label(metric)
    if "accuracy" in metric.lower() or "f1" in metric.lower():
        return f"{title} (%)"
    return title


def try_parse_float(value: str) -> float | None:
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def ordered_dimension_values(values: list[str], dimension: str) -> list[str]:
    unique_values = list(dict.fromkeys(values))

    if dimension == "ratio" and "Baseline" in unique_values:
        others = [item for item in unique_values if item != "Baseline"]
        return ["Baseline", *others]

    parsed = [try_parse_float(item) for item in unique_values]
    if all(item is not None for item in parsed):
        pairs = list(zip(unique_values, parsed))
        pairs.sort(key=lambda item: item[1])
        return [name for name, _ in pairs]

    return unique_values


def apply_tight_ylim(
    ax,
    values_by_group: dict[str, np.ndarray],
    errors_by_group: dict[str, np.ndarray],
    global_range: bool,
) -> None:
    if global_range:
        return

    low_candidates: list[float] = []
    high_candidates: list[float] = []

    for group_name, y in values_by_group.items():
        yerr = errors_by_group[group_name]
        valid_mask = np.isfinite(y)
        if not np.any(valid_mask):
            continue
        y_valid = y[valid_mask]
        yerr_valid = yerr[valid_mask]
        low_candidates.extend((y_valid - yerr_valid).tolist())
        high_candidates.extend((y_valid + yerr_valid).tolist())

    if low_candidates and high_candidates:
        y_min = float(min(low_candidates))
        y_max = float(max(high_candidates))
        span = max(y_max - y_min, 1e-6)
        pad = max(0.5, span * 0.08)
        ax.set_ylim(y_min - pad, y_max + pad)


def prompt_customize_axes() -> tuple[str, str, str]:
    inquirer = get_inquirer_module()

    first = inquirer.prompt(
        [
            inquirer.List(
                "chart_dim",
                message="What should define each chart?",
                choices=["method", "split", "ratio"],
            )
        ]
    )
    if not first:
        raise SystemExit("Customization cancelled.")

    chart_dim = first["chart_dim"]
    remaining = [item for item in ["method", "split", "ratio"] if item != chart_dim]

    second = inquirer.prompt(
        [
            inquirer.List(
                "x_dim",
                message="What should go on the x-axis?",
                choices=remaining,
            )
        ]
    )
    if not second:
        raise SystemExit("Customization cancelled.")

    x_dim = second["x_dim"]
    group_dim = next(item for item in remaining if item != x_dim)
    return chart_dim, x_dim, group_dim


def build_custom_records(
    selected_tables: list[tuple[int, dict]],
    forced_group_field: str | None,
) -> tuple[list[dict], dict]:
    records: list[dict] = []
    method_order: list[str] = []
    split_order: list[str] = []
    ratio_order: list[str] = []

    split_label = "Split"
    ratio_label = "Ratio"
    metric_name = "metric"
    mode_name = "mode"
    legend_off_by_method: dict[str, bool] = {}

    for idx, table in selected_tables:
        rows = table.get("rows") or []
        if not rows:
            continue

        group_field = forced_group_field or infer_group_field(rows[0])
        method_container_key = infer_method_container_key(rows, group_field)
        headers = table.get("headers") or []

        split_label = headers[0] if headers else prettify_label(group_field)
        if method_container_key is not None:
            ratio_label = prettify_label(method_container_key)

        method_value = str(table.get("method_name") or f"table_{idx}")
        if method_value not in method_order:
            method_order.append(method_value)
        legend_off_by_method[method_value] = legend_is_off(table)

        metric_name = str(table.get("metric", metric_name))
        mode_name = str(table.get("mode", mode_name))

        header_ratio_order = headers[2:] if len(headers) > 2 else []

        for row in rows:
            split_value = str(row.get(group_field, ""))
            if split_value not in split_order:
                split_order.append(split_value)

            baseline_mean, baseline_err = parse_latex_value(row.get("baseline", ""))
            if not math.isnan(baseline_mean):
                if "Baseline" not in ratio_order:
                    ratio_order.insert(0, "Baseline")
                records.append(
                    {
                        "method": method_value,
                        "split": split_value,
                        "ratio": "Baseline",
                        "value": baseline_mean,
                        "err": baseline_err,
                    }
                )

            method_map = {}
            if method_container_key is not None and isinstance(row.get(method_container_key), dict):
                method_map = row.get(method_container_key) or {}

            ordered_keys = [
                key for key in header_ratio_order if key in method_map
            ]
            ordered_keys.extend(
                key for key in method_map.keys() if key not in ordered_keys
            )

            for ratio_value in ordered_keys:
                if ratio_value not in ratio_order:
                    ratio_order.append(ratio_value)
                mean, err = parse_latex_value(method_map.get(ratio_value, ""))
                if math.isnan(mean):
                    continue
                records.append(
                    {
                        "method": method_value,
                        "split": split_value,
                        "ratio": str(ratio_value),
                        "value": mean,
                        "err": err,
                    }
                )

    metadata = {
        "mode": mode_name,
        "metric": metric_name,
        "legend_off_by_method": legend_off_by_method,
        "labels": {
            "method": "Method",
            "split": split_label,
            "ratio": ratio_label,
        },
        "orders": {
            "method": ordered_dimension_values(method_order, "method"),
            "split": ordered_dimension_values(split_order, "split"),
            "ratio": ordered_dimension_values(ratio_order, "ratio"),
        },
    }
    return records, metadata


def plot_customized_views(
    records: list[dict],
    metadata: dict,
    chart_dim: str,
    x_dim: str,
    group_dim: str,
    output_dir: Path | None,
    dpi: int,
    global_range: bool,
    title_override: str | None,
    xlabel_override: str | None,
    ylabel_override: str | None,
    show_baseline_line: bool,
    title_font: float | None,
    axis_title_font: float | None,
    tick_font: float | None,
    bar_spacing: float,
    bar_gap: float,
) -> None:
    if not records:
        raise ValueError("No plottable records found for customized plotting.")

    labels = metadata["labels"]
    orders = metadata["orders"]
    metric = metadata["metric"]
    legend_off_by_method = metadata.get("legend_off_by_method", {})

    chart_values = orders[chart_dim]
    persistent_x_order: list[str] | None = None
    apply_x_order_to_remaining = False
    persistent_group_order: list[str] | None = None
    apply_group_order_to_remaining = False

    def prompt_left_to_right_order(
        inquirer_module,
        items: list[str],
        confirm_message: str,
        pick_message: str,
    ) -> list[str] | None:
        response = inquirer_module.prompt(
            [inquirer_module.Confirm("reorder", message=confirm_message, default=False)]
        )
        if not response or not response.get("reorder"):
            return None

        remaining = list(items)
        ordered: list[str] = []
        while remaining:
            pick_response = inquirer_module.prompt(
                [
                    inquirer_module.List(
                        "pick",
                        message=pick_message,
                        choices=remaining,
                    )
                ]
            )
            if not pick_response:
                break
            choice = pick_response.get("pick")
            if choice is None:
                break
            ordered.append(choice)
            remaining.remove(choice)

        return ordered if ordered else None

    for chart_value in chart_values:
        subset = [item for item in records if item[chart_dim] == chart_value]
        if not subset:
            continue

        present_x = {item[x_dim] for item in subset}
        present_groups = {item[group_dim] for item in subset}

        x_values = [item for item in orders[x_dim] if item in present_x]
        group_values = [item for item in orders[group_dim] if item in present_groups]

        if not x_values or not group_values:
            continue

        # Interactive grouping order adjustment per chart
        try:
            inquirer = get_inquirer_module()
        except SystemExit:
            inquirer = None

        if apply_x_order_to_remaining and persistent_x_order is not None:
            ordered_present = [item for item in persistent_x_order if item in x_values]
            trailing = [item for item in x_values if item not in ordered_present]
            x_values = ordered_present + trailing
        elif inquirer is not None:
            x_order = prompt_left_to_right_order(
                inquirer,
                x_values,
                "Change x-axis order?",
                "Select the next left-most x-axis value:",
            )
            if x_order:
                x_values = x_order
                apply_resp = inquirer.prompt(
                    [
                        inquirer.Confirm(
                            "reuse_x",
                            message="Apply this x-axis order to remaining graphs?",
                            default=True,
                        )
                    ]
                )
                if apply_resp and apply_resp.get("reuse_x"):
                    persistent_x_order = list(x_order)
                    apply_x_order_to_remaining = True

        if apply_group_order_to_remaining and persistent_group_order is not None:
            ordered_present = [item for item in persistent_group_order if item in group_values]
            trailing = [item for item in group_values if item not in ordered_present]
            group_values = ordered_present + trailing
        elif inquirer is not None:
            resp = inquirer.prompt([
                inquirer.Confirm("reorder", message="Change grouping order?", default=False)
            ])
            if resp and resp.get("reorder"):
                remaining = list(group_values)
                new_order: list[str] = []
                while remaining:
                    choice = inquirer.prompt([
                        inquirer.List(
                            "pick",
                            message="Select the next left-most grouping:",
                            choices=remaining,
                        )
                    ])
                    if not choice:
                        break
                    pick = choice.get("pick")
                    if pick is None:
                        break
                    new_order.append(pick)
                    remaining.remove(pick)
                if new_order:
                    group_values = new_order
                    apply_resp = inquirer.prompt([
                        inquirer.Confirm(
                            "reuse",
                            message="Apply this grouping order to remaining graphs?",
                            default=True,
                        )
                    ])
                    if apply_resp and apply_resp.get("reuse"):
                        persistent_group_order = list(new_order)
                        apply_group_order_to_remaining = True

        lookup = {
            (item[x_dim], item[group_dim]): (item["value"], item["err"])
            for item in subset
        }

        # Baseline line is shown when baseline exists for every x-value and baseline bars are removed.
        baseline_by_x: dict[str, tuple[float, float]] = {}
        for x_value in x_values:
            baseline_candidates = [
                (item["value"], item["err"]) for item in subset
                if item["ratio"] == "Baseline" and item[x_dim] == x_value
            ]
            if baseline_candidates:
                baseline_by_x[str(x_value)] = baseline_candidates[0]

        show_baseline_line = (
            show_baseline_line
            and bool(baseline_by_x)
            and all(str(x_value) in baseline_by_x for x_value in x_values)
        )

        if show_baseline_line and group_dim == "ratio":
            group_values = [item for item in group_values if item != "Baseline"]

        values: dict[str, np.ndarray] = {}
        errors: dict[str, np.ndarray] = {}
        for group_value in group_values:
            y_vals = []
            y_errs = []
            for x_value in x_values:
                pair = lookup.get((x_value, group_value), (math.nan, math.nan))
                y_vals.append(pair[0])
                y_errs.append(pair[1])
            values[group_value] = np.array(y_vals, dtype=float)
            errors[group_value] = np.array(y_errs, dtype=float)

        x_pos = np.arange(len(x_values))
        n_groups = len(group_values)
        group_width = min(0.85, 0.22 * max(1, n_groups))
        bar_width = group_width / max(1, n_groups)

        fig_width = max(8, 1.1 * len(x_values) + 3)
        fig, ax = plt.subplots(figsize=(fig_width, 6))
        cmap = plt.get_cmap("tab10")
        color_by_group = {
            group_name: cmap(i % cmap.N)
            for i, group_name in enumerate(group_values)
        }

        labeled_groups: set[str] = set()
        for xi, x_center in enumerate(x_pos):
            present_groups = [
                group_value
                for group_value in group_values
                if np.isfinite(values[group_value][xi])
            ]
            if not present_groups:
                continue

            current_group_width = min(0.85, 0.22 * max(1, len(present_groups)))
            current_bar_width = current_group_width / max(1, len(present_groups))
            actual_bar_width = current_bar_width * (1.0 - bar_spacing)
            bar_step = current_bar_width * (1.0 + bar_gap)

            for i, group_value in enumerate(present_groups):
                offset = (i - (len(present_groups) - 1) / 2) * bar_step
                y = float(values[group_value][xi])
                yerr = float(errors[group_value][xi])
                if not np.isfinite(yerr):
                    yerr = 0.0

                # Resolve which method this bar originates from so per-method legend toggles apply
                # even when plotting by split/ratio combinations.
                if x_dim == "method":
                    method_for_bar = str(x_values[xi])
                elif group_dim == "method":
                    method_for_bar = str(group_value)
                else:
                    method_for_bar = str(chart_value)

                legend_allowed = not bool(legend_off_by_method.get(method_for_bar, False))
                label = str(group_value) if (legend_allowed and group_value not in labeled_groups) else "_nolegend_"
                ax.bar(
                    x_center + offset,
                    y,
                    width=actual_bar_width,
                    yerr=yerr,
                    capsize=4,
                    label=label,
                    color=color_by_group[group_value],
                    alpha=1.0,
                    edgecolor="black",
                    linewidth=0.6,
                    zorder=3,
                )
                labeled_groups.add(group_value)

        # Draw baseline dotted line and shaded error region behind bars.
        if show_baseline_line:
            bx_core = x_pos.astype(float)
            by_core = np.array([baseline_by_x[str(xv)][0] for xv in x_values], dtype=float)
            berr_core = np.array([baseline_by_x[str(xv)][1] for xv in x_values], dtype=float)

            # Extend as if two extra groups exist: one to the left and one to the right.
            bx = np.concatenate(([bx_core[0] - 1.0], bx_core, [bx_core[-1] + 1.0]))
            by = np.concatenate(([by_core[0]], by_core, [by_core[-1]]))
            berr = np.concatenate(([berr_core[0]], berr_core, [berr_core[-1]]))
            ax.fill_between(
                bx,
                by - berr,
                by + berr,
                color="#ffb3b3",
                alpha=0.35,
                zorder=-20,
                label="_nolegend_",
            )
            ax.plot(
                bx,
                by,
                color="red",
                linestyle=":",
                linewidth=2.0,
                zorder=-19,
                label="Baseline",
            )

        title_text = (
            title_override
            if title_override is not None
            else f"{labels[chart_dim]}: {chart_value} - {metric_ylabel(metric)}"
        )
        ax.set_title(title_text, fontsize=title_font)
        ax.set_xlabel(xlabel_override or labels[x_dim], fontsize=axis_title_font)
        ax.set_ylabel(ylabel_override or metric_ylabel(metric), fontsize=axis_title_font)
        ax.set_xticks(x_pos)
        ax.set_xticklabels([str(item) for item in x_values], fontsize=tick_font)
        ax.tick_params(axis="y", labelsize=tick_font)
        # Keep the visual viewport limited to real plotted groups.
        ax.set_xlim(x_pos[0] - 0.5, x_pos[-1] + 0.5)

        apply_tight_ylim(ax, values, errors, global_range)

        ax.grid(axis="y", linestyle="--", linewidth=0.6, alpha=0.5)
        show_legend = True
        if chart_dim == "method":
            show_legend = not bool(legend_off_by_method.get(str(chart_value), False))
        elif len(present_x) == 1:
            only_value = next(iter(present_x))
            if x_dim == "method":
                show_legend = not bool(legend_off_by_method.get(str(only_value), False))
        if show_legend:
            ax.legend(
                title=labels[group_dim],
                loc="best",
                fontsize=tick_font,
                title_fontsize=axis_title_font,
            )
        fig.tight_layout()

        if output_dir is not None:
            output_dir.mkdir(parents=True, exist_ok=True)
            filename = sanitize_filename(
                f"custom_{chart_dim}_{chart_value}_{x_dim}_vs_{group_dim}_{metric}"
            ) + ".png"
            output_path = output_dir / filename
            fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
            print(f"Saved figure: {output_path}")


def plot_table(
    table: dict,
    output_dir: Path | None,
    dpi: int,
    table_index: int,
    forced_group_field: str | None,
    global_range: bool,
    title_override: str | None,
    xlabel_override: str | None,
    ylabel_override: str | None,
    title_font: float | None,
    axis_title_font: float | None,
    tick_font: float | None,
    bar_spacing: float,
    bar_gap: float,
) -> None:
    rows = table.get("rows") or []
    if not rows:
        raise ValueError("Table has no rows to plot.")

    group_field = forced_group_field or infer_group_field(rows[0])
    ordered_methods, method_display_names, method_container_key = extract_methods(
        table,
        rows,
        group_field,
    )
    x_labels, values, errors = build_plot_arrays(
        rows,
        group_field,
        ordered_methods,
        method_container_key,
    )

    n_groups = len(x_labels)
    n_methods = len(ordered_methods)
    x = np.arange(n_groups)

    # Keep bars compact when there are many methods.
    group_width = min(0.85, 0.22 * max(1, n_methods))
    bar_width = group_width / max(1, n_methods)

    fig_width = max(8, 1.1 * n_groups + 3)
    fig, ax = plt.subplots(figsize=(fig_width, 6))
    cmap = plt.get_cmap("tab20")
    color_by_method = {
        method: cmap(i % cmap.N)
        for i, method in enumerate(ordered_methods)
    }

    labeled_methods: set[str] = set()
    for xi, x_center in enumerate(x):
        present_methods = [
            method for method in ordered_methods if np.isfinite(values[method][xi])
        ]
        if not present_methods:
            continue

        current_group_width = min(0.85, 0.22 * max(1, len(present_methods)))
        current_bar_width = current_group_width / max(1, len(present_methods))
        actual_bar_width = current_bar_width * (1.0 - bar_spacing)
        bar_step = current_bar_width * (1.0 + bar_gap)

        for i, method in enumerate(present_methods):
            offset = (i - (len(present_methods) - 1) / 2) * bar_step
            y = float(values[method][xi])
            yerr = float(errors[method][xi])
            if not np.isfinite(yerr):
                yerr = 0.0

            label = method_display_names.get(method, prettify_label(method))
            if method in labeled_methods:
                label = "_nolegend_"

            ax.bar(
                x_center + offset,
                y,
                width=actual_bar_width,
                yerr=yerr,
                capsize=4,
                label=label,
                color=color_by_method[method],
                alpha=1.0,
                edgecolor="black",
                linewidth=0.6,
            )
            labeled_methods.add(method)

    mode = table.get("mode", "table")
    metric = table.get("metric", "metric")
    headers = table.get("headers") or [prettify_label(group_field)]

    default_title = f"{metric_ylabel(metric)} by {prettify_label(headers[0])}"
    default_xlabel = headers[0] if headers else prettify_label(group_field)
    default_ylabel = metric_ylabel(metric)

    title = title_override or default_title
    xlabel = xlabel_override or default_xlabel
    ylabel = ylabel_override or default_ylabel

    ax.set_title(title, fontsize=title_font)
    ax.set_xlabel(xlabel, fontsize=axis_title_font)
    ax.set_ylabel(ylabel, fontsize=axis_title_font)
    ax.set_xticks(x)
    ax.set_xticklabels(x_labels, fontsize=tick_font)
    ax.tick_params(axis="y", labelsize=tick_font)

    apply_tight_ylim(ax, values, errors, global_range)

    ax.grid(axis="y", linestyle="--", linewidth=0.6, alpha=0.5)
    if not legend_is_off(table):
        ax.legend(
            title="Method",
            loc="best",
            fontsize=tick_font,
            title_fontsize=axis_title_font,
        )

    fig.tight_layout()

    if output_dir is not None:
        output_dir.mkdir(parents=True, exist_ok=True)
        filename = sanitize_filename(f"table_{table_index}_{mode}_{metric}") + ".png"
        output_path = output_dir / filename
        fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
        print(f"Saved figure: {output_path}")


def main() -> None:
    args = parse_args()

    font_dir = Path(__file__).resolve().parents[1] / "figures" / "font"
    configure_cmu_serif_font(font_dir)

    with args.json_path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)

    payload_title = payload.get("title")
    payload_xlabel = payload.get("xlabel")
    payload_ylabel = payload.get("ylabel")
    payload_baseline_line = payload.get("baseline_line")
    payload_title_font = parse_float(payload.get("title_font"))
    payload_axis_title_font = parse_float(payload.get("axis_title_font"))
    payload_tick_font = parse_float(payload.get("tick_font"))
    payload_bar_spacing = normalize_bar_spacing(payload.get("bar_spacing"))
    payload_bar_gap = normalize_bar_gap(payload.get("bar_gap"))

    tables = payload.get("tables")
    if not isinstance(tables, list) or not tables:
        raise ValueError("Input JSON must contain a non-empty 'tables' array.")

    if args.table_index is not None:
        if args.table_index < 0 or args.table_index >= len(tables):
            raise IndexError(
                f"--table-index {args.table_index} is out of range for {len(tables)} tables."
            )
        selected = [(args.table_index, tables[args.table_index])]
    else:
        selected = list(enumerate(tables))

    if args.customize:
        chart_dim, x_dim, group_dim = prompt_customize_axes()
        records, metadata = build_custom_records(
            selected_tables=selected,
            forced_group_field=args.group_field,
        )

        table_override = selected[0][1] if len(selected) == 1 else {}
        title_override = table_override.get("title") or payload_title
        xlabel_override = table_override.get("xlabel") or payload_xlabel
        ylabel_override = table_override.get("ylabel") or payload_ylabel
        show_baseline_line = parse_bool(
            table_override.get("baseline_line", payload_baseline_line),
            default=True,
        )
        title_font = parse_float(table_override.get("title_font")) or payload_title_font
        axis_title_font = (
            parse_float(table_override.get("axis_title_font"))
            or payload_axis_title_font
        )
        tick_font = parse_float(table_override.get("tick_font")) or payload_tick_font
        bar_spacing = normalize_bar_spacing(
            table_override.get("bar_spacing", payload_bar_spacing)
        )
        bar_gap = normalize_bar_gap(table_override.get("bar_gap", payload_bar_gap))

        plot_customized_views(
            records=records,
            metadata=metadata,
            chart_dim=chart_dim,
            x_dim=x_dim,
            group_dim=group_dim,
            output_dir=args.output_dir,
            dpi=args.dpi,
            global_range=args.global_range,
            title_override=title_override,
            xlabel_override=xlabel_override,
            ylabel_override=ylabel_override,
            show_baseline_line=show_baseline_line,
            title_font=title_font,
            axis_title_font=axis_title_font,
            tick_font=tick_font,
            bar_spacing=bar_spacing,
            bar_gap=bar_gap,
        )
    else:
        for idx, table in selected:
            title_override = table.get("title") or payload_title
            xlabel_override = table.get("xlabel") or payload_xlabel
            ylabel_override = table.get("ylabel") or payload_ylabel
            title_font = parse_float(table.get("title_font")) or payload_title_font
            axis_title_font = (
                parse_float(table.get("axis_title_font")) or payload_axis_title_font
            )
            tick_font = parse_float(table.get("tick_font")) or payload_tick_font
            bar_spacing = normalize_bar_spacing(
                table.get("bar_spacing", payload_bar_spacing)
            )
            bar_gap = normalize_bar_gap(table.get("bar_gap", payload_bar_gap))
            plot_table(
                table=table,
                output_dir=args.output_dir,
                dpi=args.dpi,
                table_index=idx,
                forced_group_field=args.group_field,
                global_range=args.global_range,
                title_override=title_override,
                xlabel_override=xlabel_override,
                ylabel_override=ylabel_override,
                title_font=title_font,
                axis_title_font=axis_title_font,
                tick_font=tick_font,
                bar_spacing=bar_spacing,
                bar_gap=bar_gap,
            )

    plt.show()


if __name__ == "__main__":
    main()
